### ISSUE TITLE
Invalid input parameter format for all methods

### ISSUE THREAD

**Issue by kakarotto67** [Yabko/CreditCardNumberValidator#1]
According to task (check [here](https://gist.github.com/intrueder/530b2bee09debea47272c65b8b87b087)) we expect String ("рядок з цифрами", "Приклад - "5533 1111 2222 3333""), but not Int64, as an input for these methods:
- GetCreditCardVendor
- IsCreditCardNumberValid
- GenerateNextCreditCardNumber

Please, modify your methods so we will be able to run unit tests over your code.

**Comment by Yabko** [comment]
fixed
