### ISSUE TITLE
GetCreditCardVendor returns incorrect vendors

### ISSUE THREAD

**Issue by kakarotto67** [Yabko/CreditCardNumberValidator#5]
Input | Expected output | Actual output

"3411 3411 3411 347" | American Express | message
"3714 4963 5398 431" | American Express | message
"3782 8224 6310 005" | American Express | message
"3566 0020 2036 0505" | JCB | message
"5105 1051 0510 5100" | MasterCard | message
"5555 5555 5555 4444" | MasterCard | message
"4012 8888 8888 1881" | VISA | message
"4111 1111 1111 1111" | VISA | message
"4222 2222 2222 2" | VISA  | message

**Comment by Yabko** [comment]
should be fixed now
