### ISSUE TITLE
GenerateNextCreditCardNumber generates incorrect card number

### ISSUE THREAD

**Issue by kakarotto67** [Yabko/CreditCardNumberValidator#6]
Pass "4999999999999999993" (VISA) into GenerateNextCreditCardNumber method
Expected result: error or some message as no more numbers left for VISA vendor
Actual result: "5000000000000000005" is returned, but this is not VISA vendor

**Comment by Yabko** [comment]
it wasn't specified in the task that the next generated number must belong to the same vendor :)
But, fixed.
